# fly.toml app configuration file generated for customer-management-app-bridge on 2024-01-18T15:38:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-management-app-bridge"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
