# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "customer-management"
client_id = "6c78fc1e472898df7f47647212bb5e78"
application_url = "https://perth-baking-settings-mem.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_customers, write_customers"

[auth]
redirect_urls = [
  "https://perth-baking-settings-mem.trycloudflare.com/auth/callback",
  "https://perth-baking-settings-mem.trycloudflare.com/auth/shopify/callback",
  "https://perth-baking-settings-mem.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shopefypro-thien-dev.myshopify.com"
